[env:esp-wrover-kit-8m]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200

; パーティションテーブル指定
board_build.partitions = partition_table.csv

; PSRAM を有効化
board_build.psram = true

; 8MB フラッシュ指定
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608

lib_deps =
  ROBOTIS-GIT/Dynamixel2Arduino